### ISSUE TITLE
Alternative Library

### ISSUE THREAD

**Issue by eorroe** [evenfrost/bulk#1]
Hey check out [NodeList.js](https://github.com/eorroe/NodeList.js). When I built this, I had the same problem (it was written in ES6) most people didn't like that, because not every browser supports it.

You could use babel to conver to ES5, but your better off writing it yourself in purely ES5, it'll be shorter and probably more performant (that's what I did) but I think you'll like NodeList.js :)

**Comment by evenfrost** [comment]
@eorroe I am up for any reasonable improvement to obscure element collections API (and I hope DOM 4 will fix that), though NodeList.js and bulk utilize quite different approaches. As far I can see with quick look, your wrapper inherits `HTMLDivElement` interface, which is only one type of many. What if I want to get value of all input fields on the page? `$$('input').value` will return `undefined` as expected as there is no inheritance of `HTMLInputElement`.
Also, mimicking Array prototype methods seems a bit imperative for me, and in my opinion it's better to convert `NodeList` collections to Array right away as there are no reasonable benefits of using static collection over mere array (and you get all the profit of array prototype in this case).

**Comment by eorroe** [comment]
@evenfrost this started as a proposal, but then I made it into a library. If this was to be actually natively implemented in browsers it'd be done with `ES6 proxies` so that `$$('input').value` will not return undefined.

To get around that in ES5, there's the method `get()`:

``` JS
$$('input').get('value'); // returns the values
```

I chose `HTMLDivElement` because its the only element that has all the properties/methods that every other element has without any special properties/methods. Besides `align` which is obselete/deprecated but hasn't been removed because of backwards compatibility I assume.

> Also, mimicking Array prototype methods seems a bit imperative for me

My library does have the Array methods, some are altered like the `push` method, to only allow you to push `Nodes` and throw an Error if something else is pushed.

So you do get all the Array methods that make sense for an Array of Nodes.

`join()` is not inherited because it doesn't make sense to use it on a `NodeList`

But if you were to map out the `textContent` of a `NodeList`:

``` JS
$$('.child').textContent.join(); // 'text,text,text'
```

Please take a look at the whole README.

Thanks for the reply.
